name: Fetch latest journal feeds (3-day window)

on:
  workflow_dispatch:
  schedule:
    - cron: '15 */6 * * *'  # every 6 hours

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install feedparser httpx
      - name: Build data
        run: |
          python scripts/build.py
      - name: Commit & push if changed
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.email "actions@github.com"
            git config user.name "GitHub Actions"
            git add -A
            git commit -m "Update articles.json"
            git push
          fi
